export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_  REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_  REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_ REGISTER_FAIL';
